name: vicon
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.8
  - bioconda::vsearch
  - bioconda::minimap2
  - conda-forge::matplotlib
  - conda-forge::ipykernel
  - conda-forge::pandas
  - conda-forge::biopython
  - conda-forge::openpyxl
