name: vicon-test
channels:
  - conda-forge
dependencies:
  - bioconda::minimap2
  - bioconda::vsearch
  - conda-forge::biopython
  - conda-forge::ipykernel
  - conda-forge::matplotlib
  - conda-forge::openpyxl
  - conda-forge::pandas
  - python=3.11.8
  - conda-forge::pyyaml
