package:
  name: vicon
  version: 0.1.0

source:
  path: ..

build:
  noarch: python
  script: |
    pip install .
    install -Dm755 vicon/scripts/ViralMSA.py $PREFIX/bin/viralmsa

requirements:
  build:
    - python >=3.11
    - pip
    - setuptools
  run:
    - python >=3.11
    - numpy 
    - pandas
    - matplotlib
    - vsearch
    - pyyaml

about:
  home: https://github.com/EhsanKA/vicon
  license: MIT
  summary: "VICON - Viral Conserved Sequence Extraction Toolkit"