package:
  name: vicon
  version: 1.0.3
  build: 1

source:
  path: ..

build:
  noarch: python
  script: |
    pip install .
    install -Dm755 vicon/scripts/ViralMSA.py $PREFIX/bin/viralmsa

requirements:
  build:
    - python >=3.11,<3.12
    - pip
    - setuptools
  run:
    - python >=3.11,<3.12
    - numpy >=2.2.6
    - pandas >=2.2.3
    - matplotlib >=3.10.3
    - bioconda::vsearch >=1.1.0
    - pyyaml >=6.0.2
    - biopython >=1.85
    - minimap2 >=2.30
    - pip

test:
  imports:
    - vicon
    - vicon.dereplication
    - vicon.alignment
    - vicon.processing
    - vicon.visualization
    - vicon.io
    - vicon.utils

about:
  home: https://github.com/EhsanKA/vicon
  license: MIT
  summary: "VICON - Viral Conserved Sequence Extraction Toolkit"