project_path: "my_projects/vicon/"
virus_name: "rsva_algo1_python"

input_sample: "data/rsva/samples/RSVA_1973-2023-10.fasta"
input_reference: "data/rsva/reference/EPI_ISL_412866_RSVA_ref.fasta"

email: "email@address.com"
kmer_size: 150
threshold: 147
l_gene_start: 8000
l_gene_end: 16000
coverage_ratio: 0.5
sort_by_mismatches: true

min_year: 2020
threshold_ratio: 0.01
drop_old_samples: false
drop_mischar_samples: true
